import products from "./products";
function Card({p}){return <article className="card"><div className="thumb">{p.icon}<span>CYBER MODZ</span></div><div className="cardBody"><div className="tag">{p.category}</div><h3>{p.name}</h3><p>{p.description}</p><div className="cardBottom"><strong>{p.price}</strong><a className="productBtn" href={"/products/"+p.slug}>View Product</a></div></div></article>}
export default function Home(){return <main><header className="nav"><a className="logo" href="/">CYBER<span>MODZ</span></a><nav><a href="#products">Products</a><a href="#categories">Categories</a><a href="#faq">FAQ</a><a href="#support">Support</a></nav><div className="navBtns"><a className="ghost" href="#">Login</a><a className="primary" href="#support">Discord</a></div></header>
<section className="hero"><div className="heroText"><div className="eyebrow">● FIVE M COMMUNITY</div><h1>UPGRADE YOUR<br/><span>FIVE M EXPERIENCE.</span></h1><p>Discover premium vehicles, EUP, maps, scripts and graphics for your server.</p><div className="heroBtns"><a className="primary big" href="#products">Explore Mods →</a><a className="ghost big" href="#support">Join Discord</a></div><div className="stats"><div><b>500+</b><small>Products</small></div><div><b>10K+</b><small>Users</small></div><div><b>24/7</b><small>Support</small></div></div></div><div className="heroVisual"><div className="visualBox"><b>CYBER<br/>MODZ</b><small>PREMIUM STORE</small></div></div></section>
<section id="categories" className="section"><div className="sectionHead"><div><span className="mini">BROWSE</span><h2>Categories</h2></div></div><div className="categories">{["🚗 Vehicles","👕 EUP / Clothes","🏙️ Maps / MLO","⚙️ Scripts","🔫 Weapons","🎨 Graphics"].map(x=><a href="#products" key={x}>{x}<span>→</span></a>)}</div></section>
<section id="products" className="section"><div className="sectionHead"><div><span className="mini">SHOP</span><h2>Featured Mods</h2></div></div><div className="grid">{products.map(p=><Card key={p.slug} p={p}/>)}</div></section>
<section className="banner" id="support"><div><span className="mini">COMMUNITY</span><h2>Need help with your server?</h2><p>Join our Discord for updates and support.</p></div><a className="primary big" href="#">Join Discord →</a></section>
<section id="faq" className="section faq"><div className="sectionHead"><div><span className="mini">HELP</span><h2>FAQ</h2></div></div><details><summary>How do I receive my product?</summary><p>Your purchase and license will appear in your account after checkout is connected.</p></details><details><summary>Are products compatible with FiveM?</summary><p>Compatibility and requirements will be shown on each product page.</p></details><details><summary>Where can I get support?</summary><p>Use the CYBER MODZ Discord community.</p></details></section>
<footer><div className="logo">CYBER<span>MODZ</span></div><p>Premium FiveM resources for creators.</p><div className="footerLinks"><a href="#products">Products</a><a href="#faq">FAQ</a><a href="#">Terms</a><a href="#">Privacy</a></div><small>© 2026 CYBER MODZ. All rights reserved.</small></footer></main>}
